version: 0.1
            
phases:

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - composer install

artifacts:
  files:
    - app/*
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
